name: Code checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint_check:
    name: Lint check
    uses: apify/workflows/.github/workflows/python_lint_check.yaml@v0.45.0
    with:
      python_versions: '["3.10", "3.11", "3.12", "3.13"]'
      install_command: uv pip install --system -e ".[dev]"
      lint_command: ruff check src tests && ruff format --check src tests

  type_check:
    name: Type check
    uses: apify/workflows/.github/workflows/python_type_check.yaml@v0.45.0
    with:
      python_versions: '["3.10", "3.11", "3.12", "3.13"]'
      install_command: uv pip install --system -e ".[dev]"
      type_check_command: mypy src

  unit_tests:
    name: Unit tests
    uses: apify/workflows/.github/workflows/python_unit_tests.yaml@v0.45.0
    with:
      python_versions: '["3.10", "3.11", "3.12", "3.13"]'
      operating_systems: '["ubuntu-latest"]'
      install_command: uv pip install --system -e ".[dev]"
      run_tests_command: pytest -q
